### PR TITLE
Fixes async gap handling in Trace.parse and Chain.parse

### PR DESCRIPTION
**Pull request by ghost**
This fixes two minor issues in dealing with async gaps at the end of stack traces (which is new with --lazy-async-stacks):
- `Chain.parse` would naively split a chain on the gaps, creating traces for every part, including the empty string after the ending gap marker.
- `Trace._parseVM` incorrectly assumed it would always be passed non-empty strings.

This was observed causing crashes in Pub tests that were parsing and checking specific traces.

### CODE REVIEW

**Comment by natebosch** [comment]
Do you know what SDK version makes this change? Will we need to try to backpublish this?

**Review by natebosch — APPROVED** [review]
Can you also update the version in `pubspec.yaml` to match the new changelog entry, including the `-dev`

**Comment by ghost** [comment]
That's a good question.
The changes behind `--lazy-async-stacks` was landed way back in https://github.com/dart-lang/sdk/commit/d5dbf106726071a8c5be9b88c53d47b9485bc73c, but additional changes have landed over a period since then. So pinpointing an exact version might take a bit a digging.

But for backpublishing I think this change should be safe regardless. It only really fixes some input corner cases, which worst case doesn't get exercised.

Whether we need to backpub. is another question.
For _our_ use I suppose not, assuming we can get Dart/Flutter to upgrade to the next version.
And the only way anyone else would have been able to hit this issue earlier was if they were running with the flag, and happened to trigger the issue - which based on the lack of other reports I take it hasn't happened.

How about we publish as usual. Then we can revisit a backpub. if anything turns up?

**Comment by mkustermann** [comment]
It doesn't take long, so to be on the safe side we can back-port this (i.e. https://github.com/dart-lang/stack_trace/commit/a076d21bf36d3de22f0b552ff515f2aec5c9e76f, https://github.com/dart-lang/stack_trace/commit/45319bfd2a6da228d8c32b06e1da02ad199373c7) and release a `1.9.5+1`. That would avoid the need to synchronize this feature with NNBD releases.

@natebosch Could you help us get this published on pub?

(Maybe it would make sense to change the "Publisher" on pub.dev to be `dart.dev` - then everyone on team could publish?)

**Comment by mkustermann** [comment]
@natebosch I saw you have the open PR https://github.com/dart-lang/stack_trace/pull/92 to publish. Should we make a new branch for `1.9.5+1` containing the two commits, so we can also publish a `1.9.5+1` release?

It would unblock some Dart VM changes to land.

**Comment by natebosch** [comment]
Sure, I can work on the backport publish. It will be published as `1.9.6`.

**Comment by mkustermann** [comment]
Thanks a lot, @natebosch !

**Pull request merged**
